### ISSUE TITLE
i18n supports of the survey page

### ISSUE THREAD

**Issue by WillemJiang** [tapjdey/InnerSource_Project_Fitness#1]
I just did some research on the i18n of shiny and find out [this project](https://github.com/Appsilon/shiny.i18n).
In this way can separate the display text with the code and ask help from community to do the translation work.

I will send out a PR for it with shortly.

**Comment by tapjdey** [comment]
The Likert scale choices aren't translating. I think the "shinyWidgets" package doesn't play well with "shiny.i18n". I can do a workaround by listing the choices on the top when the language changes. Let me know if you have a better solution.

**Comment by tapjdey** [comment]
Chinese Translation complete
